# This is a basic CI build workflow using GitHub Actions
name: compile_linux64b

# Controls when the action will run. 
on:
  # Triggers this workflow on push to master or pull requests to master.
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job called "compile"
  compile:
    # Simply run "make" on latest ubuntu image provided by GitHub
    runs-on: ubuntu-latest
    steps:
      # Check-out repository
      - uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Run test.bin
        run: ./test.bin
